create table
  public.barrel_inventory (
    id bigint generated by default as identity not null,
    name text not null,
    potion_type integer[] null,
    quantity integer null,
    constraint barrel_inventory_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_item (
    id bigint generated by default as identity not null,
    cart_id integer not null,
    sku text null,
    quantity integer null,
    constraint cart_item_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts (
    id bigint generated by default as identity not null,
    customer_id integer not null,
    constraint carts_pkey primary key (id),
    constraint carts_id_key unique (id)
  ) tablespace pg_default;

create table
  public.customer (
    id bigint generated by default as identity not null,
    name text not null,
    class text null,
    level integer null,
    constraint customer_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_inventory (
    id bigint generated by default as identity not null,
    sku text not null,
    name text null,
    quantity integer null,
    price integer null,
    in_catalog boolean null,
    potion_type integer[] null,
    target_amount integer null,
    constraint potion_inventory_pkey primary key (id),
    constraint potion_inventory_id_key unique (id)
  ) tablespace pg_default;

  create table
  public.shop_balance (
    id bigint generated by default as identity not null,
    gold integer not null default 0,
    ml_capacity integer null,
    potion_capacity integer null,
    constraint shop_balance_pkey primary key (id)
  ) tablespace pg_default;



